latest i3 + polybar

diff --git a/misc/bin/autostart b/misc/bin/autostart
--- a/misc/bin/autostart
+++ b/misc/bin/autostart
@@ -1,4 +1,18 @@
 #!/bin/bash
 
-redshift &
-slack &
+term=$(which kitty || xterm)
+autopath="$HOME/.config/autostart"
+
+errout() {
+    echo "ERROR: $@"
+    exit 1
+}
+
+[[ -d $autopath ]] || errout "$autopath doesn't exist"
+for f in $(find $autopath); do
+    exe=$(cat $f | grep 'Exec=')
+    echo $exe
+done
+
+#redshift &
+#slack &
